### ISSUE TITLE
Add note map

### ISSUE THREAD

**Issue by jonahsnider** [team581/2024-offseason-bot#15]
Note map tech needs to be finalized on comp bot, then we can port it to this codebase

**Comment by saikiranra** [comment]
Currently no plan to add the Note camera to this robot - do we want it? I think it makes sense to focus the vision efforts on this robot to the 2 april tag cams.

**Comment by jonahsnider** [comment]
That seems reasonable. If note map seems promising (ex. it performs well at Chezy) and we have time down the line, we can evaluate if it'd be useful on this robot for MTTD.

**Comment by jonahsnider** [comment]
Cancelled in favor of intake assist tech as an alternative to the full note map functionality
