### ISSUE TITLE
Research auto tooling

### ISSUE THREAD

**Issue by jonahsnider** [team581/2024-offseason-bot#57]
Decide the tech stack we want to use for autos on this robot.

Paths:
- Choreo 2024
- PathPlanner 2024
- Choreo 2025
- PathPlanner 2025
- In code?

Autos:
- PathPlanner 2024
- PathPlanner 2025
- In code

**Comment by saikiranra** [comment]
Can we commit to using the note camera to intake at least center line notes?

**Comment by fcuellar13** [comment]
Paths & autos will use Pathplanner 2025
